# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: VSBuild@1
  inputs:
    solution: '${{parameters.solutionName}}'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="${{parameters.artifactStagingDirectory}}"'
    platform: '${{parameters.buildPlatform}}'
    configuration: '${{parameters.buildConfiguration}}'
    clean: true
    restoreNugetPackages: true
    msbuildArchitecture: 'x64'
 
#---Build
- template: templates/buildTemplate.yml
  parameters:
    solutionName: '$(solution)'
    buildPlatform: '$(buildPlatform)'
    buildConfiguration: '$(buildConfiguration)'
    artifactStagingDirectory: '$(build.artifactStagingDirectory)'

#---Publish
- template: templates/publish.yml
  parameters:
    artifactstagingdirectory: '$(build.artifactStagingDirectory)'