# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

# pool:
#   vmImage: 'windows-latest'

trigger:
- uat

parameters:
- name: image
  displayName: Pool Image
  type: string
  default: windows-latest
  values:
    - windows-latest
    - windows-2019
    - ubuntu-latest
    - macOS-latest
    - macOS-10.15

- name: solution
  displayName: Solution type (Choose .csproj for .NET Core app & .sln for ASP.NET app)
  type: string
  values:
    - '**/*.csproj'  
    - '**/*.sln'

- name:  versionSpec
  displayName: Nuget Tool Version 
  type: string
  default: 6.0.0
  values:
    - "6.2.1"
    - "6.2.0"
    - "6.1.0"
    - "6.0.0"
    - "6.0.2"
    - "5.11.2"
    - "5.11.2"

jobs:
- job: build
  displayName: build
  pool: 
    vmImage: $(parameters.image)
  steps:
  - script: echo building $(Build.BuildNumber) with ${{ parameters.image }}

# Nuget Tool Installer task
  - template: ./templates/build_templates/NuGetToolInstaller_template.yml
    parameters:
      solutionName: '$(parameters.solution)'
      versionSpec: '${{ parameters.versionSpec }}'

# Build Template 
  - template: ./templates/build_templates/build_template.yml
    parameters:
      solutionName: '${{ parameters.solution }}'

# Artifact Template    
  - template: ./templates/build_templates/Artifact_template.yml
    # parameters:
    #   solutionName: '${{ parameters.solution }}'
      
# variables:

#   #Build variables
#   solution: '**/*.csproj'
#   buildPlatform: 'Any CPU'
#   buildConfiguration: 'Release'
  
#   #Deploy variables
#   azureSubscription: 'CSP-Competency Dev-IMS App Ops-Mohammed khaja Pasha(3dc3cd1a-d5cd-4e3e-a648-b2253048af83)'
#   appName: 'SampleWebappDeployment'
#   appType: 'webApp'
#   deploymentMethod: 'auto'
#   package: '$(System.DefaultWorkingDirectory)/**/*.zip'

#   #SonarQube variables
#   SonarQube: 'Sonar'
#   scannerMode: 'MSBuild'
#   projectKey: 'BuildTemplate_BuildTemplate_AYCOwWbt5hTFp9NdoVHg'
#   projectName: 'sonar.projectName'
#   pollingTimeoutSec: '300'

# steps:

# # - task: SonarQubePrepare@5
# #   inputs:
# #     SonarQube: 'Sonar'
# #     scannerMode: 'MSBuild'
# #     projectKey: 'BuildTemplate_BuildTemplate_AYCOwWbt5hTFp9NdoVHg'
# #     projectName: 'sonar.projectName'

# #SonarQube
# #Prepare Analysis Configuration
# - template: ./templates/SonarQube_templates/PrepareAnalysisConfiguration_template.yml
#   parameters:
#     SonarQube: '$(SonarQube)'
#     scannerMode: '$(scannerMode)'
#     projectKey: '$(projectKey)'
#     projectName: '$(projectName)'

# #---Build
#   - template: ./templates/build_templates/buildTemplate.yml
#     parameters:
# #     solutionName: '$(solution)'
# #     buildPlatform: '$(buildPlatform)'
# #     buildConfiguration: '$(buildConfiguration)'
#       artifactStagingDirectory: '$(build.artifactStagingDirectory)'
#       DefaultWorkingDirectory: '$(System.DefaultWorkingDirectory)'

# # Deploy on webApp service https://samplewebappdeployment.azurewebsites.net/
# - template: ./templates/deployment_templates/WebApp_template.yml
#   parameters:
#     azureSubscription: '$(azureSubscription)'
#     appType: '$(appType)'
#     appName: '$(appName)'
#     package: '$(package)'
#     deploymentMethod: '$(deploymentMethod)'

# # - task: AzureWebApp@1
# # inputs:
# #    azureSubscription: 'CSP-Competency Dev-IMS App Ops-Mohammed khaja Pasha(1)(3dc3cd1a-d5cd-4e3e-a648-b2253048af83)'
# #    appType: 'webApp'
# #    appName: 'SampleWebappDeployment'
# #    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
# #    deploymentMethod: 'auto'
    
# #SonarQube    
# #Run Code Analysis
# - task: SonarQubeAnalyze@5

# #SonarQube
# #Publish Quality Gate Result
# - template: ./templates/SonarQube_templates/PublishQualityGateResult_template.yml
#   parameters:
#     pollingTimeoutSec: '$(pollingTimeoutSec)'
   
# - task: SonarQubePublish@5
#   inputs:
#     pollingTimeoutSec: '300'
